ALTER TABLE formations ADD COLUMN IF NOT EXISTS category_id VARCHAR(100);
ALTER TABLE formations ADD COLUMN IF NOT EXISTS certified BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE seances ALTER COLUMN video_key TYPE VARCHAR(500);
