param(
    [Parameter(Mandatory = $true)]
    [string]$AuthUrl,

    [Parameter(Mandatory = $true)]
    [string]$ResourceUrl,

    [string]$AndroidProjectDir = (Resolve-Path "$PSScriptRoot\..\..\elearning-android").Path,

    [switch]$Release
)

$ErrorActionPreference = "Stop"

function Ensure-TrailingSlash([string]$value) {
    if ($value.EndsWith("/")) { return $value }
    return "$value/"
}

$AuthUrl = Ensure-TrailingSlash $AuthUrl
$ResourceUrl = Ensure-TrailingSlash $ResourceUrl

$file = Join-Path $AndroidProjectDir "local.properties"
$props = [ordered]@{}

if (Test-Path $file) {
    Get-Content $file | ForEach-Object {
        if ($_ -match "^\s*([^#][^=]*)=(.*)$") {
            $props[$matches[1].Trim()] = $matches[2]
        }
    }
}

if ($Release) {
    $props["RELEASE_AUTH_SERVER_URL"] = $AuthUrl
    $props["RELEASE_RESOURCE_SERVER_URL"] = $ResourceUrl
}
else {
    $props["AUTH_SERVER_URL"] = $AuthUrl
    $props["RESOURCE_SERVER_URL"] = $ResourceUrl
}

$lines = @(
    "# Generated by deployment/scripts/set-android-backend.ps1",
    "# Keep this file local. Do not commit real environment values."
)

foreach ($key in $props.Keys) {
    $lines += "$key=$($props[$key])"
}

Set-Content -LiteralPath $file -Value $lines -Encoding UTF8
Write-Host "Updated $file"
